apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: lab-placement
  namespace: default
spec:
  numberOfClusters: 1
  clusterSets:
    - lab
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            env: lab
